"""ledger_query.py — query submissions/ledger.jsonl.

Usage:
    python sec-research/scripts/ledger_query.py --list
    python sec-research/scripts/ledger_query.py --status submitted
    python sec-research/scripts/ledger_query.py --venue ghsa
    python sec-research/scripts/ledger_query.py --trace FIND-2026-05-07-001
    python sec-research/scripts/ledger_query.py --update-index
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

HOOKS_DIR = Path(__file__).resolve().parent.parent / "hooks"
sys.path.insert(0, str(HOOKS_DIR))

from lib.paths import LEDGER_PATH, DOCS_DIR  # noqa: E402
from lib import ledger  # noqa: E402


def _print_entry(e: dict) -> None:
    fields = ["entry_id", "event_type", "trace_id", "venue", "outcome", "actor", "logged_at"]
    print(" | ".join(f"{k}={e.get(k, '-')}" for k in fields))


def cmd_list(args) -> int:
    entries = ledger.read_all()
    for e in entries:
        _print_entry(e)
    print(f"\n{len(entries)} entries in {LEDGER_PATH}")
    return 0


def cmd_status(args) -> int:
    entries = [e for e in ledger.read_all() if e.get("outcome") == args.status]
    for e in entries:
        _print_entry(e)
    return 0


def cmd_venue(args) -> int:
    entries = [e for e in ledger.read_all() if e.get("venue") == args.venue]
    for e in entries:
        _print_entry(e)
    return 0


def cmd_trace(args) -> int:
    entries = ledger.find_by_trace(args.trace)
    for e in entries:
        _print_entry(e)
    return 0


def cmd_update_index(args) -> int:
    """Rebuild docs/INDEX.md from ledger + findings/."""
    entries = ledger.read_all()

    # Map trace_id -> latest status
    status_by_trace: dict[str, dict] = {}
    for e in entries:
        tid = e.get("trace_id")
        if not tid:
            continue
        if e.get("event_type") in ("submission-succeeded", "submission-failed", "status-transition"):
            status_by_trace[tid] = e

    # Read finding titles from finding.md frontmatter
    from lib.paths import FINDINGS_DIR
    titles: dict[str, str] = {}
    if FINDINGS_DIR.exists():
        for d in FINDINGS_DIR.iterdir():
            if not d.is_dir():
                continue
            fm_md = d / "finding.md"
            if fm_md.exists():
                try:
                    import re as _re
                    content = fm_md.read_text(encoding="utf-8")
                    m_title = _re.search(r"^title:\s*[\"']?(.*?)[\"']?$", content, _re.MULTILINE)
                    m_trace = _re.search(r"^trace_id:\s*(\S+)", content, _re.MULTILINE)
                    if m_trace:
                        titles[m_trace.group(1)] = m_title.group(1) if m_title else "(no title)"
                except Exception:
                    continue

    # Build markdown table
    lines = [
        "# Trace-ID Index",
        "",
        "Append-only registry of every finding produced in this workspace. Auto-generated by `ledger_query.py --update-index`.",
        "",
        "| Trace ID | Title | Status | Venue | Submission ID |",
        "|----------|-------|--------|-------|---------------|",
    ]
    all_traces = sorted(set(list(titles.keys()) + list(status_by_trace.keys())))
    for tid in all_traces:
        title = titles.get(tid, "?")
        ev = status_by_trace.get(tid, {})
        status = ev.get("outcome") or ev.get("to_status") or "-"
        venue = ev.get("venue") or "-"
        sub_id = ev.get("submission_id") or "-"
        lines.append(f"| `{tid}` | {title} | {status} | {venue} | {sub_id} |")
    if not all_traces:
        lines.append("| (no findings yet) | | | | |")

    out = DOCS_DIR / "INDEX.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Index updated at {out} ({len(all_traces)} findings)")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description="Query the submission ledger.")
    sub = p.add_subparsers()
    p.add_argument("--list", action="store_true", help="List all entries")
    p.add_argument("--status", help="Filter by outcome (submitted, accepted, rejected, ...)")
    p.add_argument("--venue", help="Filter by venue")
    p.add_argument("--trace", help="Show all events for a trace_id")
    p.add_argument("--update-index", action="store_true", help="Rebuild docs/INDEX.md")
    args = p.parse_args()

    if args.update_index:
        return cmd_update_index(args)
    if args.trace:
        return cmd_trace(args)
    if args.status:
        return cmd_status(args)
    if args.venue:
        return cmd_venue(args)
    return cmd_list(args)


if __name__ == "__main__":
    sys.exit(main())
