"""sign_approval.py — interactive issuance of submission approval tokens.

Approval tokens authorize a SPECIFIC trace_id to be submitted to a SPECIFIC venue.
Generated by THIS script; honored by PT-2 hook in submit.py invocations.

Workflow:
1. Run verify_finding.py first; sign_approval refuses if verification didn't pass.
2. Show full finding summary.
3. Require user to TYPE the trace_id to confirm (no y/n; deliberate friction).
4. Sign + write token to submissions/tokens/<token-id>.json.
5. Append approval-issued event to ledger.

Usage: python sec-research/scripts/sign_approval.py FIND-2026-05-07-001 --venue ghsa
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

HOOKS_DIR = Path(__file__).resolve().parent.parent / "hooks"
sys.path.insert(0, str(HOOKS_DIR))

from lib.paths import SUBMISSIONS_TOKENS_DIR, FINDINGS_DIR  # noqa: E402
from lib.sign_verify import sign_token  # noqa: E402
from lib import ledger  # noqa: E402

VENUE_CHOICES = ["huntr", "ghsa", "ibb-h1", "h1", "bugcrowd", "intigriti", "direct-maintainer", "manual-form"]


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _next_token_id() -> str:
    today = _utc_now().strftime("%Y-%m-%d")
    counter = 1
    if SUBMISSIONS_TOKENS_DIR.exists():
        for p in SUBMISSIONS_TOKENS_DIR.glob(f"apv-{today}-*.json"):
            m = re.search(r"apv-\d{4}-\d{2}-\d{2}-(\d{3})", p.name)
            if m:
                n = int(m.group(1))
                if n >= counter:
                    counter = n + 1
    return f"apv-{today}-{counter:03d}"


def _find_finding_dir(trace_id: str) -> Path | None:
    if not FINDINGS_DIR.exists():
        return None
    for d in FINDINGS_DIR.iterdir():
        if d.is_dir() and trace_id in d.name:
            return d
    return None


def _load_finding_summary(finding_dir: Path) -> dict:
    """Load relevant summary fields from finding.md frontmatter + verification.json."""
    summary = {
        "trace_id": "?",
        "title": "?",
        "vuln_class": "?",
        "severity": {},
        "target": {},
        "status": "?",
        "deduplication_check": {},
    }
    finding_md = finding_dir / "finding.md"
    if finding_md.exists():
        try:
            import yaml
            content = finding_md.read_text(encoding="utf-8")
            m = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
            if m:
                fm = yaml.safe_load(m.group(1)) or {}
                summary.update({k: fm.get(k, summary.get(k)) for k in summary})
        except Exception as exc:
            summary["_load_error"] = str(exc)

    verif = finding_dir / "verification.json"
    if verif.exists():
        try:
            with verif.open("r", encoding="utf-8") as f:
                v = json.load(f)
            summary["_verification_ok"] = v.get("ok", False)
            summary["_verified_at"] = v.get("verified_at")
        except Exception:
            summary["_verification_ok"] = False
    else:
        summary["_verification_ok"] = False
    return summary


def main() -> int:
    p = argparse.ArgumentParser(description="Sign a submission approval token (interactive).")
    p.add_argument("trace_id")
    p.add_argument("--venue", required=True, choices=VENUE_CHOICES)
    p.add_argument("--ttl-hours", type=float, default=4.0, help="TTL in hours (max 24; default 4)")
    p.add_argument("--test-mode-confirm", action="store_true", help="Skip interactive confirmation (TESTS ONLY)")
    args = p.parse_args()

    finding_dir = _find_finding_dir(args.trace_id)
    if finding_dir is None:
        print(f"ERROR: no finding directory matching {args.trace_id}", file=sys.stderr)
        return 1

    summary = _load_finding_summary(finding_dir)

    if not summary.get("_verification_ok"):
        print("ERROR: finding has not passed verify_finding.py. Run verification first:", file=sys.stderr)
        print(f"  python sec-research/scripts/verify_finding.py {args.trace_id}", file=sys.stderr)
        return 1

    print("\n" + "=" * 75)
    print("  APPROVAL REQUEST — Type the trace-id to confirm submission")
    print("=" * 75)
    print(f"  Trace ID    : {summary.get('trace_id')}")
    print(f"  Title       : {summary.get('title')}")
    sev = summary.get("severity") or {}
    print(f"  Vuln class  : {summary.get('vuln_class')}")
    print(f"  Severity    : CVSS v3.1 {sev.get('cvss_v3_1_score', '?')} ({sev.get('cvss_v3_1_vector', '?')})")
    target = summary.get("target") or {}
    print(f"  Target      : {target.get('asset_type', '?')}={target.get('identifier', '?')}@{target.get('version_or_revision', '?')}")
    print(f"  Venue       : {args.venue}")
    dc = summary.get("deduplication_check") or {}
    print(f"  Dedup check : {dc.get('checked_at', '<not run>')} (matches: {len(dc.get('matches', []))})")
    print(f"  Verification: PASSED at {summary.get('_verified_at')}")
    print("=" * 75)

    if args.test_mode_confirm:
        confirmed = True
    else:
        try:
            answer = input(f"\nType the trace-id ({args.trace_id}) to confirm: ").strip()
        except EOFError:
            print("ERROR: no input received; aborting", file=sys.stderr)
            return 1
        confirmed = answer == args.trace_id

    if not confirmed:
        print("Aborted (input didn't match trace-id). No token issued.")
        return 1

    now = _utc_now()
    expires_at = now + timedelta(hours=args.ttl_hours)
    token_id = _next_token_id()

    payload = {
        "token_id": token_id,
        "trace_id": args.trace_id,
        "venue": args.venue,
        "created_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "expires_at": expires_at.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "max_uses": 1,
    }
    try:
        signature = sign_token(payload)
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    payload["signature"] = signature

    SUBMISSIONS_TOKENS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = SUBMISSIONS_TOKENS_DIR / f"{token_id}.json"
    with out_path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)

    ledger.append_event(
        "approval-issued",
        approval_token_id=token_id,
        trace_id=args.trace_id,
        venue=args.venue,
        notes=f"approved by {summary.get('_verified_at', '?')}",
    )

    print(f"\nApproval token issued: {token_id}")
    print(f"Submit with:")
    print(f"  python sec-research/scripts/submit.py --trace {args.trace_id} --token {token_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
